import Head from "next/head";
import { NavBar } from "@/components/Navbar/NavBar";
import { Movie } from "@/components/Movie/Movie";
import { MainContent } from "@/layouts/MainContent";
import { MovieGrid } from "@/layouts/MovieGrid/MovieGrid";
import { useQuery } from "@apollo/client";
import { GET_MOVIES } from "@/graphql/queries/movieQueries";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const movieRes = useQuery(GET_MOVIES, { variables: { limit: 12 } });

  if (movieRes.error) return <p>Error : {movieRes.error.message}</p>;

  return (
    <>
      <Head>
        <title>Cinematic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <NavBar />

      <MainContent title="Recent Movies" isLoading={movieRes.loading}>
        <MovieGrid>
          {movieRes?.data?.get_movies.map((movie: any) => {
            return (
              <Movie
                id={movie.id}
                key={movie.id}
                name={movie.name}
                rating={movie.rating}
                type={movie.type}
                imageUrl={movie.image}
              />
            );
          })}
        </MovieGrid>
      </MainContent>
    </>
  );
}
