import Head from "next/head";
import { NavBar } from "@/components/Navbar/NavBar";
import { Movie } from "@/components/Movie/Movie";
import { MainContent } from "@/layouts/MainContent";
import { useState } from "react";
import { MovieGrid } from "@/layouts/MovieGrid/MovieGrid";
import movies from "../../data/movies.json";
import styles from "@/styles/Home.module.scss";

export default function Home() {
  const [loading, setLoading] = useState(true);

  function handleLoading() {
    setTimeout(() => {
      setLoading(false);
    }, 2000);
  }

  handleLoading();

  return (
    <>
      <Head>
        <title>Cinematic</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <NavBar />

      <MainContent title="Recent Movies" isLoading={loading}>
        <MovieGrid>
          {movies.map((movie) => {
            return (
              <Movie
                key={movie.id}
                name={movie.name}
                rating={movie.rating}
                type={movie.type}
                imageUrl={movie.image}
              />
            );
          })}
        </MovieGrid>
      </MainContent>
    </>
  );
}
